### ISSUE TITLE
Pkg.test() fails on 1.10.0-rc1

### ISSUE THREAD

**Issue by j-fu** [marius311/CompositeStructs.jl#12]
Hi, `Pkg.test()` fails on version 1.10.0-rc1, while `include("test/runtests.jl")` is ok.

The point appears to be that after `@composite struct Bar`, `struct Bar` also overwrites constructor methods. During precompilation (which is somehow happening with `Pkg.test()` but not with `include("test/runtests.jl")`), Julia 1.10 does not like method overwriting, it is ok with exactly redefining structs .
 
Lots of discussions on this, e.g https://github.com/JuliaLang/julia/issues/52213

The package works, it is the way it's being tested which fails

Unfortumately I was not able to come up with a PR fixing this.

**Comment by marius311** [comment]
Thanks for catching this, fixed by https://github.com/marius311/CompositeStructs.jl/commit/28ff37b50c5e4407a8923baa812abf560b0ce5c6, will tag shortly.

**Comment by marius311** [comment]
(the issue btw wasnt precompilation related, its just that Pkg.test turns on method-overwritten warnings whereas when you launch from the commandline theyre off by default)
